# 开发环境
server:
  port: 18080
spring:
  datasource:
    url: jdbc:mysql://sh-cynosdbmysql-grp-d6dt8ttk.sql.tencentcdb.com:24689/oauth_template?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: lige1204@
  redis:
    host: os.redis-65.ryecloud.cn
    port: 16379
    password: 1204+
    database: 7

# 单点登录配置
sso:
  # 是否开启
  active: true
  #登录页面地址
  server: http://127.0.0.1:3000
  #登录服务地址
  api: http://127.0.0.1:23000
  token:
    # Token生成模式 1 - UUID 2 - JWT
    model: 2

# jwt配置
jwt:
  # 密钥
  secret: OAUTH_TEMPLATE_1204
  # 过期时间 单位: 秒
  expire: 7200